Add terraform to CI (#86)

diff --git a/jenkins/ci/Jenkinsfile b/jenkins/ci/Jenkinsfile
--- a/jenkins/ci/Jenkinsfile
+++ b/jenkins/ci/Jenkinsfile
@@ -45,6 +45,7 @@ pipeline {
                         ]
                     }
                 }
+
                 stage('Build and Test') {
                     steps {
                         script {
@@ -68,6 +69,34 @@ pipeline {
                         }
                     }
                 }
+
+                stage('Terraform') {
+                    steps {
+                        dir('terraform') {
+                            sh 'terraform fmt -check'
+                            sh 'terraform init'
+
+                            withEnv([
+                                "AWS_ACCESS_KEY_ID=${params.AWS_ACCESS_KEY_ID}",
+                                "AWS_SECRET_ACCESS_KEY=${params.AWS_SECRET_ACCESS_KEY}",
+                                "AWS_DEFAULT_REGION=${params.AWS_REGION}",
+                                "TF_VAR_postgres_db=${params.POSTGRES_DB}",
+                                "TF_VAR_postgres_user=${params.POSTGRES_USER}",
+                                "TF_VAR_postgres_password=${params.POSTGRES_PASSWORD}",
+                                "TF_VAR_postgres_host=${params.POSTGRES_HOST}"
+                            ]) {
+                                sh 'terraform plan -no-color -out=terraform.tfplan'
+                            }
+
+                            sh '''
+                                if [ ! -f terraform.tfplan ]; then
+                                    echo "Plan file not created, failing the job."
+                                    exit 1
+                                fi
+                            '''
+                        }
+                    }
+                }
             }
         }
 
@@ -78,6 +107,11 @@ pipeline {
                     docker system prune -f --all --volumes
                 '''
             }
+        }
+    }
+    post {
+        always {
+            cleanWs()
         }
     }
 }
