Fix CD secrets and add CI check for Terraform (#48)
* Update workflow env vars

* Update CD secrets

* Add CI check for terraform

* Add TF vars to CI

* Update CI

* Output tf plan file

* Remove TF state module

* Fix TF bug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,3 +51,51 @@ jobs:
 
       - name: Tear down the Stack
         run: docker compose -f docker-compose.local.yml down
+
+  terraform:
+    name: "Terraform Format and Plan Check"
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: terraform
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.9.7
+          terraform_wrapper: false
+
+      - name: Terraform Format Check
+        run: |
+          terraform fmt -check
+
+      - name: Terraform Init
+        run: |
+          terraform init
+
+      - name: Terraform Plan
+        env:
+          TF_VAR_postgres_db: ${{ secrets.POSTGRES_DB }}
+          TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
+          TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
+          TF_VAR_postgres_host: ${{ secrets.POSTGRES_HOST }}
+        run: |
+          terraform plan -no-color -out=terraform.tfplan
+
+      - name: Validate Plan Output
+        run: |
+          if [ ! -f terraform.tfplan ]; then
+            echo "Plan file not created, failing the job."
+            exit 1  # Fail the job if the plan file is not created
+          fi
